### ISSUE TITLE
Initializing in swift

### ISSUE THREAD

**Issue by ghost** [ArtSabintsev/UIView-AutoLayoutView#1]
I cant seem to figure out how to initialize with autoLayoutNew in Swift. I've loaded your library using a bridging header file. Can you please help?

**Comment by ArtSabintsev** [comment]
Sure. Without playing around with it first, I think it should be:

``` swift
let aView = UIView.newAutoLayoutView()
```

**Comment by ArtSabintsev** [comment]
Also, if you have some UIView subclass, like `MyAwesomeView`, it should be:

``` swift
let aView = MyAwesomeView.newAutoLayoutView()
```

**Comment by ghost** [comment]
Thank you for your reply. I was under the impression I could also use this for regular UIView / UIImageView, was I wrong?

``` swift
let aView = UIView.newAutoLayoutView()
```

but this doesn't work for me..

**Comment by ArtSabintsev** [comment]
I'll take a look tonight and get back to you.

**Comment by ghost** [comment]
Thank you! After I set this code manually all your other functions work like a charm

``` swift
setTranslatesAutoresizingMaskIntoConstraints(false)
```

(sorry, im new to commengint on git, feels dumb)

**Comment by ArtSabintsev** [comment]
hah, no problem. SO everything works?

**Comment by ghost** [comment]
Well, it all seems to work accept that I still need to setTranslates... to false manually and can not do this while initializing with newAutoLayoutView()

It would help me if you could take a look and see why it doesn't seem to work in Swift, but there's no big hurry

**Comment by ArtSabintsev** [comment]
I'll take a look, as I'm doing most of my programming in Swift these days. When I figure it out (later tonight), I'll make a post here :)

**Comment by ArtSabintsev** [comment]
I just pushed v1.0.2, fixing a small issue and adding Swift documentation to the readme. Hope this helps!
